default_platform(:android)
platform :android do
  desc "Run unit tests"
  lane :test do
    gradle(task: "test")
  end
  desc "Build debug APK"
  lane :beta do
    gradle(task: "assembleDebug")
  end
end